### PR TITLE
added setup script, fixed issue #1, fixed mac filtering

### LINKED ISSUE #1: escape '%' when encoding device ID.
Hi there, device ID's can contain %. (For example if a product class were G-240G-P genie would encode this as part of the device id as G%2D240G%2DP.

This:

requests.utils.quote(device_id)

Needs to be:

requests.utils.quote(device_id, safe='%')

Great module by the way! I was in the process of writing the same when I stumbled upon yours :)

### PR DESCRIPTION
**Pull request by liisberg**
Fixes #1, adds a setup script and fixes filtering by MAC adresses.

### CODE REVIEW

**Comment by liisberg** [comment]
Any chance of getting this merged @okraits?

**Comment by okraits** [comment]
I'm sorry, I didn't originally see this PR. I will have a look at it next week!

**Comment by liisberg** [comment]
Sounds good @okraits! Happy to make more contributions!

Will you consider adding the "hacktoberfest-accepted" label to this PR?
Thanks in advance.

**Comment by liisberg** [comment]
@okraits  Any updates?

**Comment by liisberg** [comment]
@okraits Bump

**Comment by federicoemartinez** [comment]
Is this going to get merged?

**Pull request closed without merging**
